# digit constants
SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = 60
SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE
SECONDS_IN_DAY = SECONDS_IN_HOUR * 24
SECONDS_IN_MONTH = SECONDS_IN_DAY * 30
SECONDS_IN_YEAR = SECONDS_IN_DAY * 365